apiVersion: apps/v1
kind: Deployment
metadata:
  name: attu
  namespace: milvus
  labels:
    app: attu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attu
  template:
    metadata:
      labels:
        app: attu
    spec:
      containers:
        - name: attu
          image: zilliz/attu:v2.2.6
          ports:
            - containerPort: 3000
          env:
            - name: MILVUS_URL
              value: "milvus-standalone:19530"
          resources:
            requests:
              cpu: "200m"
              memory: "500Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: attu
  namespace: milvus
spec:
  type: NodePort
  ports:
    - name: http
      port: 8000
      targetPort: 3000
      nodePort: 30005
  selector:
    app: attu
