apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: milvus
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2023-03-20T20-16-18Z
          command:
            - minio
            - server
            - /minio_data
          ports:
            - containerPort: 9000
          env:
            - name: MINIO_ACCESS_KEY
              value: "minioadmin"
            - name: MINIO_SECRET_KEY
              value: "minioadmin"
          volumeMounts:
            - name: minio-data
              mountPath: /minio_data
          resources:
            requests:
              cpu: "200m"
              memory: "500Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
      volumes:
        - name: minio-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: milvus
spec:
  type: NodePort
  ports:
    - name: minio
      port: 9000
      nodePort: 30002
  selector:
    app: minio
